# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TRAFIKVERKET_API_KEY: ${{ secrets.TRAFIKVERKET_API_KEY }}
      ATLAS_USERNAME: ${{ secrets.ATLAS_USERNAME }}
      ATLAS_PASSWORD: ${{ secrets.ATLAS_PASSWORD }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    # First steps is for backend, make sure to change use frontend folder when adding frontend test
    - name: Install backend dependencies
      run: cd backend && npm install

    - name: Run backend tests
      run: cd backend && npm test

    - name: Cypress run
      uses: cd frontend-vue && cypress-io/github-action@v6
    
    - name: Install frontend dependencies
      run: cd frontend-vue && npm install

    - name: Run frontend tests
      run: cd frontend-vue && npm cy:run --e2e
